### ISSUE TITLE
Epic: Feed deletion

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#651]
## Background

> Blocking is important and empowering, and it’s one of the primary tools that we have to set our boundaries on the network. Most clients will hide content from blocked users, but today that data still exists in your Scuttlebutt database. This is mostly fine for most blocking scenarios, but there are some scenarios where that data needs to get off of your computer immediately.
>
> -- <ssb:message:sha256:p9lmpwpWCT5GiNYejJDntM8fyBff-t4-TfVUEKq1EKY=>

This thread should serve as a tracking issue for context on all of the random commits, branches, pull requests, issues, and posts about feed deletion (epic/megathread as suggested by @dominictarr on our call yesterday).

## Requirements

- Deletion method should be available via ssb-server API.
- Relevant messages must be deleted immediately.
- Views that support one-off deletion may delete those individual items.
- Other views must rebuild without the deleted messages.

## Implementation

- [x] https://github.com/flumedb/flumedb/issues/25
- [x] https://github.com/flumedb/flumedb/pull/26
- [x] https://github.com/flumedb/flumedb/issues/27
- [x] https://github.com/flumedb/flumedb/pull/28
- [x] https://github.com/flumedb/flumedb/pull/29
- [x] https://github.com/flumedb/flumedb/pull/30
- [x] https://github.com/flumedb/aligned-block-file/issues/4
- [x] https://github.com/flumedb/flumedb/issues/31
- [x] https://github.com/flumedb/flumeview-level/issues/15
- [ ] https://github.com/flumedb/flumeview-reduce/issues/10
- [x] https://github.com/flumedb/aligned-block-file/pull/5
- [x] https://github.com/flumedb/flumelog-offset/pull/16
- [x] https://github.com/flumedb/flumedb/pull/33
- [x] https://github.com/flumedb/flumelog-level/pull/2
- [x] https://github.com/flumedb/aligned-block-file/pull/6
- [x] https://github.com/flumedb/test-flumelog/issues/1
- [x] https://github.com/fraction/flumedb-delete/pull/4
- [x] https://github.com/flumedb/flumelog-offset/pull/17
- [x] https://github.com/flumedb/flumedb/pull/34
- [x] https://github.com/ssbc/ssb-db/issues/260
- [x] https://github.com/flumedb/flumeview-hashtable/pull/3
- [x] https://github.com/flumedb/flumeview-level/issues/16
- [x] https://github.com/flumedb/flumeview-level/pull/17
- [x] https://github.com/ssbc/patchwork/pull/1026
- [x] https://github.com/flumedb/aligned-block-file/issues/7
- [x] https://github.com/flumedb/aligned-block-file/pull/8
- [x] https://github.com/ssbc/ssb-db/issues/261
- [x] https://github.com/flumedb/aligned-block-file/pull/9
- [x] https://github.com/ssbc/muxrpc/issues/47
- [x] https://github.com/flumedb/flumeview-hashtable/pull/4
- [x] https://github.com/flumedb/flumeview-level/pull/19
- [x] https://github.com/flumedb/flumeview-level/pull/20
- [x] https://github.com/flumedb/flumeview-level/pull/21
- [x] https://github.com/ssbc/ssb-db/pull/262
